#!/usr/bin/env python3
"""Generate SUMMARY.md and validate Doctrine's navigation.

Two modes:

    python3 scripts/gen_nav.py            Rewrite SUMMARY.md from the tree.
    python3 scripts/gen_nav.py --check    Report navigation defects, exit 1.

The check enforces three rules:

1. Every guide under guides/ is linked from README.md.
2. Every guide is linked from the README.md of its own directory.
3. No navigation file links to a repository path that does not exist.

It also reports when SUMMARY.md is stale relative to the tree.
"""

import re
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple
from urllib.parse import unquote

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SUMMARY_FILE = PROJECT_ROOT / "SUMMARY.md"
ROOT_README = PROJECT_ROOT / "README.md"

# Markdown inline links: [text](target), optionally angle-bracketed or titled.
LINK_RE = re.compile(r"\]\(\s*<?([^)<>\s]+)>?(?:\s+\"[^\"]*\")?\s*\)")
HEADING_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
TITLE_SUFFIXES = (" Style Guide", " Guide")
EXTERNAL_PREFIXES = ("http://", "https://", "mailto:", "tel:", "//")

GENERATED_BANNER = "<!-- Generated by scripts/gen_nav.py. Do not edit by hand. -->"


def relative(path: Path) -> str:
    """Repository-relative POSIX path."""
    return path.relative_to(PROJECT_ROOT).as_posix()


def title_for(path: Path) -> str:
    """Human title for a file: its first H1, else the file name."""
    if path.suffix in {".md", ".markdown"}:
        try:
            match = HEADING_RE.search(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError):
            match = None
        if match:
            title = match.group(1).strip()
            for suffix in TITLE_SUFFIXES:
                if title.endswith(suffix) and len(title) > len(suffix):
                    title = title[: -len(suffix)]
            return title.strip()
    return path.name


def sorted_files(directory: Path, pattern: str, keep_dotfiles: bool) -> List[Path]:
    files = [p for p in directory.glob(pattern) if p.is_file()]
    if not keep_dotfiles:
        files = [p for p in files if not p.name.startswith(".")]
    return sorted(files, key=lambda p: p.name)


def sorted_dirs(directory: Path) -> List[Path]:
    return sorted((p for p in directory.iterdir() if p.is_dir()), key=lambda p: p.name)


def guide_categories() -> List[Path]:
    """Top-level guide category directories, alphabetically."""
    return sorted_dirs(PROJECT_ROOT / "guides")


def guides_in(directory: Path) -> List[Path]:
    """Non-README markdown guides directly inside a directory."""
    return [p for p in sorted_files(directory, "*.md", False) if p.name != "README.md"]


def all_guides() -> List[Path]:
    """Every non-README guide anywhere under guides/."""
    return sorted(
        (
            p
            for p in (PROJECT_ROOT / "guides").rglob("*.md")
            if p.is_file() and p.name != "README.md"
        ),
        key=lambda p: relative(p),
    )


def all_category_readmes() -> List[Path]:
    """Every README.md under guides/, including nested categories."""
    return sorted(
        (p for p in (PROJECT_ROOT / "guides").rglob("README.md") if p.is_file()),
        key=lambda p: relative(p),
    )


def link_targets(source: Path) -> List[Tuple[str, Optional[Path]]]:
    """Local link targets in a markdown file as (raw, resolved-or-None) pairs.

    External links, anchors and paths escaping the repository resolve to None.
    """
    try:
        content = source.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return []

    targets: List[Tuple[str, Optional[Path]]] = []
    for raw in LINK_RE.findall(content):
        target = raw.strip()
        if not target or target.startswith("#"):
            continue
        if target.lower().startswith(EXTERNAL_PREFIXES):
            continue
        target = unquote(target.split("#", 1)[0].split("?", 1)[0])
        if not target:
            continue
        resolved = (source.parent / target).resolve()
        try:
            resolved.relative_to(PROJECT_ROOT)
        except ValueError:
            targets.append((raw, None))
            continue
        targets.append((raw, resolved))
    return targets


def linked_paths(source: Path) -> set:
    return {resolved for _, resolved in link_targets(source) if resolved is not None}


def build_summary() -> str:
    lines: List[str] = ["# Summary", "", GENERATED_BANNER, ""]

    lines += [
        f"- [Doctrine]({relative(ROOT_README)})",
        f"- [Agent Instructions]({relative(PROJECT_ROOT / 'AGENTS.md')})",
        f"- [Changelog]({relative(PROJECT_ROOT / 'CHANGELOG.md')})",
        "",
        "## Guides",
        "",
    ]

    for category in guide_categories():
        readme = category / "README.md"
        if readme.exists():
            lines.append(f"- [{title_for(readme)}]({relative(readme)})")
        else:
            lines.append(f"- {title_for(category)}")
        for guide in guides_in(category):
            lines.append(f"  - [{title_for(guide)}]({relative(guide)})")
        for subdir in sorted_dirs(category):
            sub_readme = subdir / "README.md"
            if sub_readme.exists():
                lines.append(f"  - [{title_for(sub_readme)}]({relative(sub_readme)})")
            else:
                lines.append(f"  - {title_for(subdir)}")
            for guide in guides_in(subdir):
                lines.append(f"    - [{title_for(guide)}]({relative(guide)})")

    lines += ["", "## Reference Material", ""]
    lines += tree_section(PROJECT_ROOT / "reference", keep_dotfiles=False)

    lines += ["", "## Configuration", ""]
    lines += tree_section(PROJECT_ROOT / "configs", keep_dotfiles=True)

    lines += ["", "## Agents", ""]
    lines += tree_section(PROJECT_ROOT / "agents", keep_dotfiles=False)

    lines += ["", "## Commands", ""]
    for command in sorted_files(PROJECT_ROOT / "commands", "*.md", False):
        lines.append(f"- [{title_for(command)}]({relative(command)})")

    lines.append("")
    return "\n".join(lines)


def tree_section(root: Path, keep_dotfiles: bool) -> List[str]:
    """One bullet per subdirectory, nesting its files and one level of children."""
    lines: List[str] = []
    for entry in sorted_files(root, "*", keep_dotfiles):
        lines.append(f"- [{title_for(entry)}]({relative(entry)})")
    for directory in sorted_dirs(root):
        lines.append(f"- {directory.name}/")
        for entry in sorted_files(directory, "*", keep_dotfiles):
            lines.append(f"  - [{title_for(entry)}]({relative(entry)})")
        for subdir in sorted_dirs(directory):
            lines.append(f"  - {subdir.name}/")
            for entry in sorted(
                (p for p in subdir.rglob("*") if p.is_file()),
                key=lambda p: relative(p),
            ):
                if not keep_dotfiles and entry.name.startswith("."):
                    continue
                lines.append(f"    - [{title_for(entry)}]({relative(entry)})")
    return lines


def check_navigation() -> List[str]:
    problems: List[str] = []

    readme_links = linked_paths(ROOT_README)
    category_links: Dict[Path, set] = {
        readme: linked_paths(readme) for readme in all_category_readmes()
    }

    for guide in all_guides():
        if guide not in readme_links:
            problems.append(f"MISSING from README.md: {relative(guide)}")
        category_readme = guide.parent / "README.md"
        if not category_readme.exists():
            problems.append(
                f"MISSING category index: {relative(guide.parent)}/README.md "
                f"(required by {relative(guide)})"
            )
        elif guide not in category_links.get(category_readme, set()):
            problems.append(
                f"MISSING from {relative(category_readme)}: {relative(guide)}"
            )

    for readme in all_category_readmes():
        if readme not in readme_links:
            problems.append(f"MISSING from README.md: {relative(readme)}")
        parent_readme = readme.parent.parent / "README.md"
        if readme.parent.parent != PROJECT_ROOT / "guides" and parent_readme.exists():
            if readme not in category_links.get(parent_readme, set()):
                problems.append(
                    f"MISSING from {relative(parent_readme)}: {relative(readme)}"
                )

    problems.extend(dead_links([ROOT_README, *all_category_readmes(), SUMMARY_FILE]))

    if SUMMARY_FILE.exists():
        if SUMMARY_FILE.read_text(encoding="utf-8") != build_summary():
            problems.append("STALE: SUMMARY.md — run python3 scripts/gen_nav.py")
    else:
        problems.append("MISSING: SUMMARY.md — run python3 scripts/gen_nav.py")

    return problems


def dead_links(sources: Iterable[Path]) -> List[str]:
    problems: List[str] = []
    for source in sources:
        if not source.exists():
            continue
        for raw, resolved in link_targets(source):
            if resolved is None:
                problems.append(f"DEAD in {relative(source)}: {raw} (escapes repository)")
            elif not resolved.exists():
                problems.append(f"DEAD in {relative(source)}: {raw}")
    return problems


def main() -> None:
    args = sys.argv[1:]
    if args and args[0] in {"-h", "--help"}:
        print(__doc__)
        return

    if args == ["--check"]:
        problems = check_navigation()
        if problems:
            for problem in problems:
                print(problem)
            print(f"\nFAILURE: {len(problems)} navigation problems.")
            sys.exit(1)
        guides = len(all_guides())
        print(f"SUCCESS: {guides} guides indexed in README.md and category READMEs.")
        return

    if args:
        print(f"Unknown arguments: {' '.join(args)}", file=sys.stderr)
        sys.exit(2)

    summary = build_summary()
    SUMMARY_FILE.write_text(summary, encoding="utf-8")
    print(f"Wrote {relative(SUMMARY_FILE)} ({len(summary.splitlines())} lines).")


if __name__ == "__main__":
    main()
